channels:
  - conda-forge
  - defaults

dependencies:
  - cmake>=3.21.1
  - control
  - coveralls
  - cython
  - dill
  - git
  - Jinja2
  - jsonschema
  - make
  - pip
  - matplotlib-base
  - nlopt
  - numpy
  - openmdao
  - openpyxl
  - pandas
  - pip
  - pyside2
  - pytest
  - pytest-cov
  - python-benedict
  - pyyaml
  - ruamel_yaml
  - scipy
  - setuptools
  - smt
  - sortedcontainers
  - swig
#  - versioneer
  - pip:
    - fatpack
    - jsonmerge
    - marmot-agents
    - simpy
# Needs to be done outside of environment file:
#  - m2w64-toolchain # [win]
#  - libpython # [win]
#  - compilers # [not win]
#  - petsc4py # [not win]
#  - mpi4py # [not win]
